spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: facturas-service
              uri: ${FACTURAS_MODULE_URL:http://localhost:8081}
              predicates:
              - Path=/get/**

            - id: authentication-service
              uri: ${USERS_MODULE_URL:http://localhost:8082}
              predicates:
              - Path=/auth/**

            - id: forgot-service
              uri: ${USERS_MODULE_URL:http://localhost:8082}
              predicates:
              - Path=/forgot/**

            - id: verification-service
              uri: ${USERS_MODULE_URL:http://localhost:8082}
              predicates:
              - Path=/verification/**

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:test1234567890secretKey1234567890jwtKey1234567890test1234567890}
  public-patterns: ${PUBLIC_PATTERNS:/auth/**}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}