name: Build and Push Image (Spring Boot Buildpacks)

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  JAVA_VERSION: "21"
  # Despliegue
  CONTAINER_NAME: spring-api-gateway
  PORT: ${{ secrets.PORT }}
  CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  USERS_MODULE_URL: ${{ secrets.USERS_MODULE_URL }}
  FACTURAS_MODULES_URL: ${{ secrets.FACTURAS_MODULES_URL }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Compute image tag
        id: tag
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" =~ ^(main|master)$ ]]; then
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # PRs: construye localmente sin publicar
      - name: Build image (no publish on PR)
        if: github.event_name == 'pull_request'
        env:
          BP_JVM_VERSION: "21"
        run: |
          ./gradlew --no-daemon \
            -PimageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} \
            bootBuildImage

      # Pushes/tags: construye y publica a GHCR
      - name: Build and publish image
        if: github.event_name != 'pull_request'
        env:
          BP_JVM_VERSION: "21"
        run: |
          ./gradlew --no-daemon \
            -PimageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} \
            bootBuildImage --publishImage

  deploy:
    needs: build-and-push
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en VPS vía Docker (pull + run con variables de entorno)
        uses: appleboy/ssh-action@v0.1.7
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          PORT: ${{ env.PORT }}
          CORS_ALLOWED_ORIGINS: ${{ env.CORS_ALLOWED_ORIGINS }}
          JWT_SECRET: ${{ env.JWT_SECRET }}
          USERS_MODULE_URL: ${{ env.USERS_MODULE_URL }}
          FACTURAS_MODULES_URL: ${{ env.FACTURAS_MODULES_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: REGISTRY,IMAGE_NAME,IMAGE_TAG,CONTAINER_NAME,PORT,CORS_ALLOWED_ORIGINS,JWT_SECRET,USERS_MODULE_URL,FACTURAS_MODULES_URL,REGISTRY_USERNAME,REGISTRY_TOKEN
          script: |
            set -euo pipefail

            IMAGE="${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"

            echo "Iniciando sesión en el registro ${REGISTRY}..."
            echo "${REGISTRY_TOKEN}" | docker login "${REGISTRY}" -u "${REGISTRY_USERNAME}" --password-stdin

            echo "Haciendo pull de la imagen ${IMAGE}..."
            docker pull "${IMAGE}"

            if docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}$"; then
              echo "Deteniendo y eliminando contenedor existente ${CONTAINER_NAME}..."
              docker stop "${CONTAINER_NAME}" || true
              docker rm "${CONTAINER_NAME}" || true
            fi

            echo "Ejecutando contenedor ${CONTAINER_NAME} con variables de entorno pasadas directamente..."
            docker run -d --name "${CONTAINER_NAME}" --restart=always \
              -p "${PORT}:8080" \
              -e CORS_ALLOWED_ORIGINS="${CORS_ALLOWED_ORIGINS}" \
              -e JWT_SECRET="${JWT_SECRET}" \
              -e USERS_MODULE_URL="${USERS_MODULE_URL}" \
              -e FACTURAS_MODULES_URL="${FACTURAS_MODULES_URL}" \
              "${IMAGE}"

            echo "Limpieza de imágenes huérfanas..."
            docker image prune -f || true